// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA05VCEEeCVFXVyObc5b906ZhYWzpZcY0',
    appId: '1:345009519586:web:63789f8e75ea861841d7bb',
    messagingSenderId: '345009519586',
    projectId: 'mci-fitness',
    authDomain: 'mci-fitness.firebaseapp.com',
    storageBucket: 'mci-fitness.firebasestorage.app',
    measurementId: 'G-4PQ2B9G9DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVOqrL110uarorvCW0hr2S4Pk-57CQBq0',
    appId: '1:345009519586:android:d584a4c74425d13e41d7bb',
    messagingSenderId: '345009519586',
    projectId: 'mci-fitness',
    storageBucket: 'mci-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQrNaETfzNraNHCHVA8C2Hovyx4LqUvDU',
    appId: '1:345009519586:ios:85db6871e88582d541d7bb',
    messagingSenderId: '345009519586',
    projectId: 'mci-fitness',
    storageBucket: 'mci-fitness.firebasestorage.app',
    iosBundleId: 'com.example.mciFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQrNaETfzNraNHCHVA8C2Hovyx4LqUvDU',
    appId: '1:345009519586:ios:85db6871e88582d541d7bb',
    messagingSenderId: '345009519586',
    projectId: 'mci-fitness',
    storageBucket: 'mci-fitness.firebasestorage.app',
    iosBundleId: 'com.example.mciFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA05VCEEeCVFXVyObc5b906ZhYWzpZcY0',
    appId: '1:345009519586:web:7686e80fd9247dd141d7bb',
    messagingSenderId: '345009519586',
    projectId: 'mci-fitness',
    authDomain: 'mci-fitness.firebaseapp.com',
    storageBucket: 'mci-fitness.firebasestorage.app',
    measurementId: 'G-9BCNX4KJ8Z',
  );
}